02_source_code/owasp-blog-secure/Models/BlogEntry.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace owasp_blog_secure.Models
{
    public class BlogEntry
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public DateTime Created { get; set; }

        public Blog Blog { get; set; }

        public IdentityUser Author { get; set; }

        public List<Comment> Comments { get; set; }
    }
}

02_source_code/owasp-blog-secure/Pages/Blog/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_Blog
{
    public class CreateModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public CreateModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Blog.Add(Blog);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

02_source_code/owasp-blog-secure/Pages/Blog/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_Blog
{
    public class DeleteModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public DeleteModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Blog = await _context.Blog.FirstOrDefaultAsync(m => m.Id == id);

            if (Blog == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Blog = await _context.Blog.FindAsync(id);

            if (Blog != null)
            {
                _context.Blog.Remove(Blog);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

02_source_code/owasp-blog-secure/Pages/Blog/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_Blog
{
    public class DetailsModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public DetailsModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Blog Blog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Blog = await _context.Blog.FirstOrDefaultAsync(m => m.Id == id);

            if (Blog == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

02_source_code/owasp-blog-secure/Pages/Blog/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_Blog
{
    public class EditModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public EditModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Blog Blog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Blog = await _context.Blog.FirstOrDefaultAsync(m => m.Id == id);

            if (Blog == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Blog).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BlogExists(Blog.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BlogExists(int id)
        {
            return _context.Blog.Any(e => e.Id == id);
        }
    }
}

02_source_code/owasp-blog-secure/Pages/BlogEntry/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_BlogEntry
{
    public class CreateModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CreateModel(owasp_blog_secure.Data.ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public BlogEntry BlogEntry { get; set; }

        public async Task<IActionResult> OnPostAsync(int? blogid)
        {
            if(blogid == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            BlogEntry.Created = DateTime.Now;
            BlogEntry.Author = await _userManager.GetUserAsync(HttpContext.User);
            BlogEntry.Blog = await _context.Blog.FirstOrDefaultAsync(b => b.Id == blogid);

            _context.BlogEntry.Add(BlogEntry);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index", new { blogid = blogid });
        }
    }
}

02_source_code/owasp-blog-secure/Pages/BlogEntry/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_BlogEntry
{
    public class DeleteModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public DeleteModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public BlogEntry BlogEntry { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogEntry = await _context.BlogEntry.FirstOrDefaultAsync(m => m.Id == id);

            if (BlogEntry == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogEntry = await _context.BlogEntry.FindAsync(id);

            if (BlogEntry != null)
            {
                _context.BlogEntry.Remove(BlogEntry);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

02_source_code/owasp-blog-secure/Pages/BlogEntry/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_BlogEntry
{
    public class DetailsModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public DetailsModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public BlogEntry BlogEntry { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogEntry = await _context.BlogEntry.Include(blogEntry => blogEntry.Author).FirstOrDefaultAsync(m => m.Id == id);

            if (BlogEntry == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

02_source_code/owasp-blog-secure/Pages/BlogEntry/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_BlogEntry
{
    public class EditModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public EditModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public BlogEntry BlogEntry { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlogEntry = await _context.BlogEntry.FirstOrDefaultAsync(m => m.Id == id);

            if (BlogEntry == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(BlogEntry).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BlogEntryExists(BlogEntry.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BlogEntryExists(int id)
        {
            return _context.BlogEntry.Any(e => e.Id == id);
        }
    }
}

02_source_code/owasp-blog-secure/Pages/BlogEntry/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_BlogEntry
{
    public class IndexModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;

        public IndexModel(owasp_blog_secure.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<BlogEntry> BlogEntry { get;set; }

        public async Task OnGetAsync(int? blogid)
        {
            if (blogid != null)
            {
                BlogEntry = await _context.BlogEntry.Include(blogEntry => blogEntry.Author).Include(blogEntry => blogEntry.Blog)
                    .Where(be => be.Blog.Id == blogid).ToListAsync();
            }
            else
            {
                BlogEntry = await _context.BlogEntry.Include(blogEntry => blogEntry.Author).Include(blogEntry => blogEntry.Blog)
                    .ToListAsync();
            }
        }
    }
}

02_source_code/owasp-blog-secure/Pages/Comment/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.Pages_Comment
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly owasp_blog_secure.Data.ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CreateModel(owasp_blog_secure.Data.ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Comment Comment { get; set; }

        [BindProperty]
        public int BlogEntryId { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Comment.Author = await _userManager.GetUserAsync(HttpContext.User);
            Comment.BlogEntry = await _context.BlogEntry.Where(be => be.Id == BlogEntryId).FirstOrDefaultAsync();

            _context.Comment.Add(Comment);
            await _context.SaveChangesAsync();

            return RedirectToPage($"/BlogEntry/Details", new { id = Comment.BlogEntry.Id });
        }
    }
}

02_source_code/owasp-blog-secure/ViewComponents/CommentListViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.ViewComponents
{
    public class CommentListViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public CommentListViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int? blogEntryId)
        {
            var commentList = new List<Comment>();

            if (blogEntryId != null)
            {
                commentList = await _context.Comment.Include(comment => comment.BlogEntry).Include(comment => comment.Author)
                    .Where(c => c.BlogEntry.Id == blogEntryId).ToListAsync();
            }

            return View(commentList);
        }
    }
}

02_source_code/owasp-blog-secure/ViewComponents/CommentWriteViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using owasp_blog_secure.Data;
using owasp_blog_secure.Models;

namespace owasp_blog_secure.ViewComponents
{
    public class CommentWriteViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public CommentWriteViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int? blogEntryId)
        {
            var comment = new Comment();

            if (blogEntryId != null)
            {
                var blogEntry = await _context.BlogEntry.Where(be => be.Id == blogEntryId).FirstOrDefaultAsync();
                comment.BlogEntry = blogEntry;
            }
            
            return View(comment);
        }
    }
}

02_source_code/owasp-blog-secure/Pages/BlogEntry/Create.cshtml
@page
@model owasp_blog_secure.Pages_BlogEntry.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BlogEntry</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BlogEntry.Title" class="control-label"></label>
                <input asp-for="BlogEntry.Title" class="form-control" />
                <span asp-validation-for="BlogEntry.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogEntry.Content" class="control-label"></label>
                <textarea asp-for="BlogEntry.Content" class="form-control"></textarea>
                <span asp-validation-for="BlogEntry.Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

02_source_code/owasp-blog-secure/Pages/BlogEntry/Delete.cshtml
@page
@model owasp_blog_secure.Pages_BlogEntry.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogEntry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BlogEntry.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BlogEntry.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BlogEntry.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BlogEntry.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BlogEntry.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BlogEntry.Created)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="BlogEntry.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

02_source_code/owasp-blog-secure/Pages/BlogEntry/Details.cshtml
@page
@model owasp_blog_secure.Pages_BlogEntry.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<div>
    <h1>@Model.BlogEntry.Title</h1>
    <p class="small">@Model.BlogEntry.Created.ToLongDateString() / by @Model.BlogEntry.Author.UserName</p>
    <p>@Html.Raw(Model.BlogEntry.Content)</p>
    <hr>
    @await Component.InvokeAsync("CommentList", new { blogEntryId = @Model.BlogEntry.Id })
    @await Component.InvokeAsync("CommentWrite", new { blogEntryId = @Model.BlogEntry.Id })
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.BlogEntry.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

02_source_code/owasp-blog-secure/Pages/BlogEntry/Edit.cshtml
@page
@model owasp_blog_secure.Pages_BlogEntry.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BlogEntry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BlogEntry.Id" />
            <div class="form-group">
                <label asp-for="BlogEntry.Title" class="control-label"></label>
                <input asp-for="BlogEntry.Title" class="form-control" />
                <span asp-validation-for="BlogEntry.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogEntry.Content" class="control-label"></label>
                <textarea asp-for="BlogEntry.Content" class="form-control"></textarea>
                <span asp-validation-for="BlogEntry.Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

02_source_code/owasp-blog-secure/Pages/BlogEntry/Index.cshtml
@page
@model owasp_blog_secure.Pages_BlogEntry.IndexModel
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Index";
}

@if (SignInManager.IsSignedIn(User)) {
    <h1>Index</h1>

    <p>
        <a asp-page="Create" asp-route-blogid="@Model.BlogEntry[0].Blog.Id">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BlogEntry[0].Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BlogEntry[0].Content)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BlogEntry[0].Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BlogEntry[0].Author)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.BlogEntry) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.UserName)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>
}

@foreach (var item in Model.BlogEntry) {
    <h1>@item.Title</h1>
    <p class="small">@item.Created.ToLongDateString() / by @item.Author.UserName</p>
    <p>
        
        @if(item.Content.Length > 50){
            @item.Content.Substring(0, 50);
        } else {
            @item.Content;
        }
    </p>
    <a asp-page="/BlogEntry/Details" asp-route-id="@item.Id">Read More -></a>
    <hr>
}